/**
 * NC-SSM Full Forward Pass
 * Top-level inference pipeline
 */

#include "ncssm.h"
#include <math.h>
#include <string.h>
#include <stdio.h>

/* External: weight data (generated by export_weights.py) */
extern const float ncssm_mel_fb[];
extern const float ncssm_weights_data[];

/* Weight offset table (filled by export) */
extern const int NCSSM_W_SNR_NOISE_SCALE;
extern const int NCSSM_W_SNR_RAW_BETA;
extern const int NCSSM_W_SNR_RAW_GAMMA;
extern const int NCSSM_W_SNR_FLOOR;
extern const int NCSSM_W_PCEN;
extern const int NCSSM_W_FREQ_FLOOR;
extern const int NCSSM_W_LSG_W;
extern const int NCSSM_W_LSG_B;
extern const int NCSSM_W_LSG_FLOOR;
extern const int NCSSM_W_PATCH_PROJ_W;
extern const int NCSSM_W_PATCH_PROJ_B;
extern const int NCSSM_W_BLOCK0_NORM_G;
extern const int NCSSM_W_BLOCK0_NORM_B;
extern const int NCSSM_W_BLOCK0_IN_PROJ;
extern const int NCSSM_W_BLOCK0_CONV_W;
extern const int NCSSM_W_BLOCK0_CONV_B;
extern const int NCSSM_W_BLOCK0_SSM;
extern const int NCSSM_W_BLOCK0_OUT_PROJ;
extern const int NCSSM_W_BLOCK1_NORM_G;
extern const int NCSSM_W_BLOCK1_NORM_B;
extern const int NCSSM_W_BLOCK1_IN_PROJ;
extern const int NCSSM_W_BLOCK1_CONV_W;
extern const int NCSSM_W_BLOCK1_CONV_B;
extern const int NCSSM_W_BLOCK1_SSM;
extern const int NCSSM_W_BLOCK1_OUT_PROJ;
extern const int NCSSM_W_FINAL_NORM_G;
extern const int NCSSM_W_FINAL_NORM_B;
extern const int NCSSM_W_CLASSIFIER_W;
extern const int NCSSM_W_CLASSIFIER_B;

/* ================================================================ */

void ncssm_init(ncssm_ctx_t *ctx) {
    memset(ctx, 0, sizeof(ncssm_ctx_t));
    ctx->weights = ncssm_weights_data;
    ctx->last_label = -1;
}

void ncssm_reset(ncssm_ctx_t *ctx) {
    memset(ctx->h, 0, sizeof(ctx->h));
    ctx->audio_pos = 0;
    ctx->last_label = -1;
    ctx->last_confidence = 0.0f;
}

/* ================================================================
 * Full forward pass: audio (16000,) → logits (12,)
 * ================================================================ */
void ncssm_forward(ncssm_ctx_t *ctx, const float *audio, float *logits) {
    const float *W = ctx->weights;
    /* center=True: padded_len = audio_len + n_fft, then (padded - n_fft)/hop + 1 */
    const int T = NCSSM_AUDIO_LEN / NCSSM_HOP_LENGTH + 1; /* 101 frames with center=True */
    const int D = NCSSM_D_MODEL;
    const int DI = NCSSM_D_INNER;
    const int M = NCSSM_N_MELS;

    /* ── 1. STFT ── */
    float mag[NCSSM_N_FREQ * NCSSM_N_FRAMES];
    ncssm_stft_mag(audio, mag, NCSSM_AUDIO_LEN);

    /* ── 2. Mel Projection ── */
    float mel[NCSSM_N_MELS * NCSSM_N_FRAMES];
    ncssm_mel_projection(mag, ncssm_mel_fb, mel, T);

    /* ── 3. SNR Estimation (with running EMA) ── */
    float snr_mel[NCSSM_N_MELS * NCSSM_N_FRAMES];
    ncssm_snr_estimate_ema(mag, ncssm_mel_fb, snr_mel, T,
                           W[NCSSM_W_SNR_NOISE_SCALE],
                           W[NCSSM_W_SNR_RAW_BETA],
                           W[NCSSM_W_SNR_RAW_GAMMA]);

    /* ── 4. Learned Spectral Gate ── */
    ncssm_spectral_gate(mel, snr_mel,
                        &W[NCSSM_W_LSG_W], &W[NCSSM_W_LSG_B],
                        &W[NCSSM_W_LSG_FLOOR], T);

    /* ── 4b. Frequency-dependent floor ── */
    for (int m = 0; m < M; m++)
        for (int t = 0; t < T; t++) {
            float fl = W[NCSSM_W_FREQ_FLOOR + m];
            if (mel[m * T + t] < fl) mel[m * T + t] = fl;
        }

    /* ── 5. DualPCEN v2 ── */
    float pcen_gate_buf[NCSSM_N_FRAMES];
    ncssm_dual_pcen_v2(mel, snr_mel, &W[NCSSM_W_PCEN], pcen_gate_buf, M, T);

    /* ── 6. Instance Norm ── */
    ncssm_instance_norm(mel, M, T);

    /* ── 7. Transpose: (M, T) → (T, M) for sequence processing ── */
    float x_seq[NCSSM_N_FRAMES * NCSSM_N_MELS];
    for (int t = 0; t < T; t++)
        for (int m = 0; m < M; m++)
            x_seq[t * M + m] = mel[m * T + t];

    /* SNR also transpose */
    float snr_seq[NCSSM_N_FRAMES * NCSSM_N_MELS];
    for (int t = 0; t < T; t++)
        for (int m = 0; m < M; m++)
            snr_seq[t * M + m] = snr_mel[m * T + t];

    /* ── 8. Patch Projection: (T, 40) → (T, 37) ── */
    float feat[NCSSM_N_FRAMES * NCSSM_D_MODEL];
    for (int t = 0; t < T; t++) {
        ncssm_linear(&x_seq[t * M],
                     &W[NCSSM_W_PATCH_PROJ_W], &W[NCSSM_W_PATCH_PROJ_B],
                     &feat[t * D], M, D);
    }

    /* ── 9. SSM Blocks ×2 ── */
    float block_out[NCSSM_N_FRAMES * NCSSM_D_MODEL];
    float xz[NCSSM_N_FRAMES * (NCSSM_D_INNER * 2)];
    float x_branch[NCSSM_D_INNER * NCSSM_N_FRAMES];  /* (DI, T) for conv */
    float z_buf[NCSSM_N_FRAMES * NCSSM_D_INNER];
    float conv_out[NCSSM_D_INNER * NCSSM_N_FRAMES];
    float ssm_in[NCSSM_N_FRAMES * NCSSM_D_INNER];
    float ssm_out[NCSSM_N_FRAMES * NCSSM_D_INNER];

    for (int blk = 0; blk < NCSSM_N_LAYERS; blk++) {
        /* Get weight offsets for this block */
        int norm_g_off = (blk == 0) ? NCSSM_W_BLOCK0_NORM_G : NCSSM_W_BLOCK1_NORM_G;
        int norm_b_off = (blk == 0) ? NCSSM_W_BLOCK0_NORM_B : NCSSM_W_BLOCK1_NORM_B;
        int in_proj_off = (blk == 0) ? NCSSM_W_BLOCK0_IN_PROJ : NCSSM_W_BLOCK1_IN_PROJ;
        int conv_w_off = (blk == 0) ? NCSSM_W_BLOCK0_CONV_W : NCSSM_W_BLOCK1_CONV_W;
        int conv_b_off = (blk == 0) ? NCSSM_W_BLOCK0_CONV_B : NCSSM_W_BLOCK1_CONV_B;
        int ssm_off = (blk == 0) ? NCSSM_W_BLOCK0_SSM : NCSSM_W_BLOCK1_SSM;
        int out_proj_off = (blk == 0) ? NCSSM_W_BLOCK0_OUT_PROJ : NCSSM_W_BLOCK1_OUT_PROJ;

        /* Save residual */
        memcpy(block_out, feat, T * D * sizeof(float));

        /* LayerNorm */
        ncssm_layer_norm(feat, &W[norm_g_off], &W[norm_b_off], D, T);

        /* In projection: (T, 37) → (T, 110), split to x_branch(55) + z(55) */
        for (int t = 0; t < T; t++) {
            ncssm_linear(&feat[t * D], &W[in_proj_off], NULL,
                         &xz[t * DI * 2], D, DI * 2);
        }

        /* Split and transpose x_branch to (DI, T) for conv */
        for (int t = 0; t < T; t++) {
            for (int d = 0; d < DI; d++) {
                x_branch[d * T + t] = xz[t * DI * 2 + d];
                z_buf[t * DI + d] = xz[t * DI * 2 + DI + d];
            }
        }

        /* DWConv1d causal (DI, T) */
        ncssm_dwconv1d_causal(x_branch, &W[conv_w_off], &W[conv_b_off],
                              conv_out, DI, T, NCSSM_D_CONV);

        /* Transpose back to (T, DI) + SiLU */
        for (int t = 0; t < T; t++) {
            for (int d = 0; d < DI; d++) {
                ssm_in[t * DI + d] = ncssm_silu(conv_out[d * T + t]);
            }
        }

        /* NC-SSM scan */
        ncssm_ssm_scan(ssm_in, snr_seq, ssm_out, ctx->h[blk],
                        &W[ssm_off], T, pcen_gate_buf);

        /* Gate: y = ssm_out * silu(z) */
        for (int t = 0; t < T; t++) {
            for (int d = 0; d < DI; d++) {
                ssm_out[t * DI + d] *= ncssm_silu(z_buf[t * DI + d]);
            }
        }

        /* Out projection + residual: (T, 55) → (T, 37) */
        for (int t = 0; t < T; t++) {
            ncssm_linear(&ssm_out[t * DI], &W[out_proj_off], NULL,
                         &feat[t * D], DI, D);
            /* Add residual */
            for (int d = 0; d < D; d++) {
                feat[t * D + d] += block_out[t * D + d];
            }
        }
    }

    /* ── 10. Final LayerNorm ── */
    ncssm_layer_norm(feat, &W[NCSSM_W_FINAL_NORM_G], &W[NCSSM_W_FINAL_NORM_B],
                     D, T);

    /* ── 11. Global Average Pooling ── */
    float pooled[NCSSM_D_MODEL];
    memset(pooled, 0, sizeof(pooled));
    for (int t = 0; t < T; t++) {
        for (int d = 0; d < D; d++) {
            pooled[d] += feat[t * D + d];
        }
    }
    for (int d = 0; d < D; d++) pooled[d] /= T;

    /* ── 12. Classifier ── */
    ncssm_linear(pooled, &W[NCSSM_W_CLASSIFIER_W], &W[NCSSM_W_CLASSIFIER_B],
                 logits, D, NCSSM_N_CLASSES);
}

/* ================================================================
 * Predict: returns class index + confidence
 * ================================================================ */
int ncssm_predict(ncssm_ctx_t *ctx, const float *audio, float *confidence) {
    float logits[NCSSM_N_CLASSES];
    ncssm_forward(ctx, audio, logits);

    /* Softmax + argmax */
    ncssm_softmax(logits, NCSSM_N_CLASSES);

    int best = 0;
    for (int i = 1; i < NCSSM_N_CLASSES; i++) {
        if (logits[i] > logits[best]) best = i;
    }

    ctx->last_label = best;
    ctx->last_confidence = logits[best];
    if (confidence) *confidence = logits[best];
    return best;
}

/* ================================================================
 * Streaming: feed chunk, returns label or -1
 * ================================================================ */
int ncssm_feed(ncssm_ctx_t *ctx, const float *chunk, int n_samples) {
    /* Accumulate */
    int space = NCSSM_AUDIO_LEN - ctx->audio_pos;
    int copy = (n_samples < space) ? n_samples : space;
    memcpy(&ctx->audio_buf[ctx->audio_pos], chunk, copy * sizeof(float));
    ctx->audio_pos += copy;

    if (ctx->audio_pos < NCSSM_AUDIO_LEN) {
        return -1;  /* Still accumulating */
    }

    /* Got 1 second, classify */
    float conf;
    int label = ncssm_predict(ctx, ctx->audio_buf, &conf);

    /* Shift buffer by chunk size for sliding window */
    int shift = n_samples;
    if (shift < ctx->audio_pos) {
        memmove(ctx->audio_buf, &ctx->audio_buf[shift],
                (ctx->audio_pos - shift) * sizeof(float));
        ctx->audio_pos -= shift;
    }

    return label;
}
